version: 2
updates:
  - package-ecosystem: "gomod" # Go modules
    directory: "/" # Root directory where go.mod is located
    schedule:
      interval: "weekly" # Check for updates weekly
  - package-ecosystem: "github-actions" # Monitor GitHub Actions
    directory: "/" # Root directory
    schedule:
      interval: "weekly" # Check for updates weekly