on: [push, pull_request]
name: CI
jobs:
  analyse-and-test:
    strategy:
      matrix:
        go-version: [1.23.5]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
          stable: false
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Static Code Analysis
        run: make setup-ci && make static-code-analysis
      - name: Unit and Integration Tests
        run: |
          sudo apt-get update
          make setup-ci && make ci-all